[package]
name = "demo_chat"
version = "0.1.0"
authors = ["Lucas Poffo <ltkpoffo@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
renet = { path = "../renet" }
renet_visualizer = { path = "../renet_visualizer" }
eframe = "0.22"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.1"
log = { version = "0.4.11", features = ["std"] }
env_logger = "0.10.0"
renet_steam_transport = { path = "../renet_steam_transport", version = "0.0.1", optional = true }
steamworks = { git = "https://github.com/Noxime/steamworks-rs", rev = "2c77327", optional = true }

[features]
default = ["transport"]
transport = ["renet/transport"]
steam_transport = ["renet_steam_transport", "steamworks"]
