[package]
name = "bevy_renet"
description = "Bevy plugin for the renet crate: Server/Client network library for multiplayer games with authentication and connection management"
edition = "2021"
keywords = ["gamedev", "networking"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/lucaspoffo/renet"
version = "0.0.8"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["transport"]
transport = ["renet/transport"]
steam_transport = ["renet_steam_transport", "steamworks"]

[dependencies]


bevy = { version = "0.11", default-features = false }
renet = { path = "../renet", version = "0.0.12", features = ["bevy"] }
renet_steam_transport = { path = "../renet_steam_transport", version = "0.0.1", features = [ "bevy" ], optional = true }
steamworks = { git = "https://github.com/Noxime/steamworks-rs", rev = "2c77327", optional = true }

[dev-dependencies]
bevy = {version = "0.11", default-features = false, features = ["bevy_core_pipeline", "bevy_render", "bevy_asset", "bevy_pbr", "x11", "tonemapping_luts", "ktx2", "zstd"]}
bincode = "1.3.1"
env_logger = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
