[package]
name = "demo_bevy"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "server"
path = "src/bin/server.rs"

[dependencies]
bevy_rapier3d = "0.21.0"
bevy = { version = "0.10.0", default-features = false, features = [
    "bevy_core_pipeline",
    "bevy_asset",
    "bevy_render",
    "bevy_pbr",
    "x11",
] }
bevy_renet = { path = "../bevy_renet", features = ["steam_transport"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.1"


# Use version directly when egui is updated to 0.22
bevy_egui = { git = "https://github.com/mvlabat/bevy_egui.git", branch = "dependabot/cargo/egui-0.22.0" }
renet_visualizer = { path = "../renet_visualizer", features = ["bevy"] }
smooth-bevy-cameras = "0.8.0"
fastrand = "2.0.0"
steamworks = { git = "https://github.com/Noxime/steamworks-rs", rev = "2c77327" }
